/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Palak Agarwal
 */
public class test extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        ttest.addItem("Endoscopy");
      ttest.addItem("X-RAY");
      ttest.addItem("Sonography");
      ttest.addItem("Gastroscopy");
      ttest.addItem("Blood Test");
      ttest.addItem("Stool Test");
      ttest.addItem("Urine Test");
      ttest.addItem("MRI Test");
      ttest.addItem("DNA Diagnostic Test");
      ttest.addItem("Ultrasound");

        String g=(String)ttest.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ttest = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        chrg = new javax.swing.JTextField();

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setText("Clinical Test Detals");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setText("NAME OF TEST");

        ttest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ttestItemStateChanged(evt);
            }
        });
        ttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttestActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel24.setText("CHARGES");

        chrg.setEditable(false);
        chrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chrg, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(ttest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(chrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ttestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ttestItemStateChanged

        String g = (String) ttest.getSelectedItem();
        {
            if (g.equals("Endoscopy")) {
                chrg.setText("Rs. 1500");
            } else if (g.equals("X-RAY")) {
                chrg.setText("Rs. 500");
            } else if (g.equals("Sonography")) {
                chrg.setText("Rs. 1000");
            } else if (g.equals("Gastroscopy")) {
                chrg.setText("Rs. 780");
            } else if (g.equals("Blood Test")) {
                chrg.setText("Rs 200");
            } else if (g.equals("Stool Test")) {
                chrg.setText("Rs. 150");
            } else if (g.equals("Urine Test")) {
                chrg.setText("Rs. 50");
            } else if (g.equals("MRI Test")) {
                chrg.setText("Rs. 2500");
            } else if (g.equals("DNA Diagnostic Test")) {
                chrg.setText("Rs. 3000");
            } else if (g.equals("Ultrasound")) {
                chrg.setText("Rs. 1500");
            }
        }

    }//GEN-LAST:event_ttestItemStateChanged

    private void chrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chrgActionPerformed

    }//GEN-LAST:event_chrgActionPerformed

    private void ttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttestActionPerformed

     public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new test().setVisible(true);
            }
        });
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chrg;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JComboBox ttest;
    // End of variables declaration//GEN-END:variables
}
